import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import CartProvider from "../Context/cartContext/cartContext";
import ProductProvider from "../Context/productContext/productContext";
//Components

import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body className={inter.className}>
        <CartProvider>
          <ProductProvider>
            <Header />

            <main>{children}</main>

            <Footer />
          </ProductProvider>
        </CartProvider>
      </body>
    </html>
  );
}
