"use Client";
import { Inter } from "next/font/google";
import "./globals.css";
//Components
// import Shop from "./components/Shop/Shop";
import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";

// import Navbar from "./components/Header/Navbar/Navbar";
// import ProductProvider from "../Context/productContext/productContext";
// import CustomerProvider from "../Context/customerContext/customerContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}

        <Footer />
        {children}
      </body>
    </html>
  );
}
