###
POST http://localhost:3080/api/categories
Content-Type: application/json

{
    "title":"Lyxigt koppel",
    "description":"tralalallalaaaa"
}
###
GET http://localhost:3080/api/categories

### // GET CATEGORY BY ID(existingproduct)
GET http://localhost:3080/api/categories/65a61b4aaeb187c25e04aa82
###
