//CREATE AN ORDER
###
POST http://localhost:3080/api/orders/createorder
Content-Type: application/json

{
  
  "customer": "65aed5e33cb3c2eaff05b7be",
  "cart": [
    {"product": "65a65393a97b953852648036", "quantity": 2, "price": 280 },
    {"product": "65a65523a97b953852648040", "quantity": 1, "price": 66 }
    
  ]
}

###
//GET SPECIFIC CUSTOMER ALL ORDERS
GET http://localhost:3080/api/orders/65aed5e33cb3c2eaff05b7be
###
