###
POST http://localhost:3080/api/orders/placeorder
Content-Type: application/json

{
  "customer": "65aed5e33cb3c2eaff05b7be"

}


###


# GET http://localhost:3080/api/orders
# ###
# POST http://localhost:3080/api/orders/placeorder
# Content-Type: application/json

# ###
# POST http://localhost:3080/api/orders/placeorder
# Content-Type: application/json

# {
#   "customer": "65aed5e33cb3c2eaff05b7be"

# }


# ###

# GET http://localhost:3080/api/orders/65aed5e33cb3c2eaff05b7be