###//==============================//
###//===========PRODUCTS===========//
###//==============================//
### // CREATE PRODUCTS

POST http://localhost:3080/api/products
Content-Type: application/json

{
    "title":"FLEXIKOPPEL GIANT",
    "price":459,
    "image":"https://www.tinybuddy.se/assets/products/21409_940x.jpg?1647434784",
    "description":"Rejält, extra stort och stabilt koppel från Flexi.En säker, stark och kromad karbinhake.",
    "colors":["Svart"],
    "sizes": ["M","L","XL"],
    "categories":["Hundkoppel"]


}

### // GET ALL PRODUCTS
GET http://localhost:3080/api/products


### // GET PRODUCTS BY ID(existingproduct)
GET http://localhost:3080/api/products/65a65393a97b953852648036
###

### // GET PRODUCTS BY ID(NOT existingproduct)
GET http://localhost:3080/api/products/659421c88866f6d4715be804
###
### // GET PRODUCTS BY CATEGORY
GET http://localhost:3080/api/products/categories/Hundkoppel
###
GET http://localhost:3080/api/products/categories/${categoryTitle}
