###//==============================//
###//===========PRODUCTS===========//
###//==============================//
### // CREATE PRODUCTS
POST http://localhost:3080/api/products
Content-Type: application/json

{
    "title":"Hundkoppel",
    "price":299,
    "image":"https://bjaf.se/cdn/shop/products/hunter_3608_46958_round_12.jpg-_cmyk_10.jpg?v=1698140619&width=1000",
    "color":"red",
    "category":"Bajspåsar"


}

### // GET ALL PRODUCTS
GET http://localhost:3080/api/products


### // GET PRODUCTS BY ID(existingproduct)
GET http://localhost:3080/api/products/659421c88866f6d4715be804
###

### // GET PRODUCTS BY ID(NOT existingproduct)
GET http://localhost:3080/api/products/659421c88866f6d4715be804
###